### ISSUE TITLE
Caleb Brainstorm for 20 minutes

### ISSUE THREAD

**Issue by ZavixDragon** [EnigmaDragons/LegendaryFrailty#208]

**Comment by Kazamaru** [comment]
Plot thought: 

4 inhibitor beings keeping X kind of power bound. Anselm goes throughout the tower defeating these to get deeper where his crystal of Immortality is. After each elemental inhibitor is defeated all the battles between that and next boss are of that element.





Esoteric(Gnostic teachings)



Cryptic Form(Takes reduced damage and restores MP when hit)

Profound/Cryptic Knowledge(You always know the enemies next move - Passive)

Mystical Absorbtion (Absorbs HP from non-physical attack)

Enigmatic Invocation(Summons an ally who gets targettted instead of you. When attacked, he takes damage based upon your foes Int instead of ATK)

Preparation(Next move costs half MP)

Concentration (Regain extra MP over next 5 turns.)











Dimensional


Gravitational Suspension(Physical attack reduced, accuracy lowered) Mana per turn

Grav Pull(Does damage based upon target's height? extra dmg is Grav was suspended)

Warp Shot(Summons projectile to hit the enemies weak spot(Hybrid of Dimensional and Esoteric))

Dimensional Blink(Avoids all damage this turn. Cost 7 MP)





Martial



Reposte(20% chance when attacked to block the damage and deal dmg back - Passive) OR Active block physical atk and deal dmg in return

Hardy (when you would take tons of damage don't, instead heal some. Passive once per battle.)
